apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - args:
            - webserver
            - -p
            - "8000"
          name: airflow-webserver
          image: apache/airflow
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql://airflow_user:airflow_pass@10.98.133.169:5432/postgres
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
        - args:
            - scheduler
          name: airflow-scheduler
          image: apache/airflow
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql://airflow_user:airflow_pass@10.98.133.169:5432/postgres
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"

      initContainers:
        - args:
            - db
            - init
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql://airflow_user:airflow_pass@10.98.133.169:5432/postgres
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
          name: airflow-db-init
          image: apache/airflow
          imagePullPolicy: IfNotPresent
